---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-0
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30000  # Choose an available port between 30000-32767
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-1
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30001  # Choose an available port between 30000-32767
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-1

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-2
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30002  # Choose an available port between 30000-32767
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-2
