apiVersion: v1
kind: Pod
metadata:
  name: clean
  labels:
    app: clean
  namespace: default
spec:
  containers:
    - name: clean
      image: busybox
      command:
        - sleep
        - infinity
      env:
        - name: HOME
          value: /root
      volumeMounts:
        - mountPath: /data/db
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongodb-pvc-nodo03
