---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-nodo02
  labels:
    name: nodo02
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30001
  selector:
    app: nodo02

---
apiVersion: v1
kind: Pod
metadata:
  name: nodo02
  labels:
    app: nodo02
    service: mongodb
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m03
  containers:
    - name: nodo02
      image: mongo:7.0.12
      command:
        - "numactl"
        - "--interleave=all"
        - "mongod"
        - "--wiredTigerCacheSizeGB"
        - "0.25"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--auth"
        - "--clusterAuthMode"
        - "keyFile"
        - "--keyFile"
        - "/etc/keyfile-volume/keyfile"
        - "--setParameter"
        - "authenticationMechanisms=SCRAM-SHA-1"
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-user
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-user
              key: MONGO_INITDB_ROOT_USERNAME
      volumeMounts:
        - name: keyfile-volume
          readOnly: true
          mountPath: /etc/keyfile-volume
        - mountPath: /data/db
          name: data
  volumes:
    - name: keyfile-volume
      configMap:
        name: keyfile
        defaultMode: 0600
    - name: data
      persistentVolumeClaim:
        claimName: mongodb-pvc-nodo02
