---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-nodo03
  labels:
    name: nodo03
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30002
  selector:
    app: nodo03

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-nodo03
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nodo03
  labels:
    app: nodo03
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m04
  containers:
    - name: nodo03
      image: mongo:7.0.12
      command:
        - "numactl"
        - "--interleave=all"
        - "mongod"
        - "--wiredTigerCacheSizeGB"
        - "0.25"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--auth"
        - "--clusterAuthMode"
        - "keyFile"
        - "--keyFile"
        - "/etc/keyfile-volume/keyfile"
        - "--setParameter"
        - "authenticationMechanisms=SCRAM-SHA-1"
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-user
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-user
              key: MONGO_INITDB_ROOT_USERNAME
      volumeMounts:
        - name: keyfile-volume
          readOnly: true
          mountPath: /etc/keyfile-volume
        - mountPath: /data/db
          name: data
  volumes:
    - name: keyfile-volume
      configMap:
        name: keyfile
        defaultMode: 0600
    - name: data
      persistentVolumeClaim:
        claimName: mongodb-pvc-nodo03
